"""
cluster_study_behavior.py

Unsupervised K-Means clustering of student study BEHAVIOR (not task priority)
for the Smart Uni Guide study planner, using the OULAD dataset.

Groups students (per code_module + code_presentation + id_student) into
behavioral segments based on engagement and performance patterns, so the
planner can tailor its recommendations to how a student actually studies
(e.g. consistent-and-engaged vs. low-engagement crammer).

Run independently with:
    venv/Scripts/python ml_scripts/study-planner/cluster_study_behavior.py

Requires train_priority_model.py to have already been run once (it produces
oulad_task_level_leakage_free.csv, the input here) - this script checks for
that file and reports clearly if it's missing.
"""

import os
import sys
import time

import joblib
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

matplotlib.use("Agg")
sns.set_theme(style="whitegrid")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

DATASETS_DIR = os.path.join(BACKEND_DIR, "datasets", "study-planner")
OUTPUTS_DIR = os.path.join(BACKEND_DIR, "ml_scripts", "study-planner", "outputs")
MODELS_DIR = os.path.join(BACKEND_DIR, "trained-models", "stuyd-planner")

LEAKAGE_FREE_CSV = os.path.join(OUTPUTS_DIR, "oulad_task_level_leakage_free.csv")

os.makedirs(OUTPUTS_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

RANDOM_STATE = 42
BEHAVIOR_COLS = [
    "avg_weekly_clicks", "clicks_trend", "active_weeks_ratio", "has_vle_activity",
    "prior_avg_score", "num_of_prev_attempts", "studied_credits",
]


def section(title):
    print("\n" + "=" * 90)
    print(title)
    print("=" * 90)


# ===========================================================================
# 0. CHECK REQUIRED INPUT FILES
# ===========================================================================
section("0. CHECK REQUIRED INPUT FILES")

if not os.path.exists(LEAKAGE_FREE_CSV):
    print(f"ERROR: missing required input file: {LEAKAGE_FREE_CSV}")
    print("  Run train_priority_model.py first to generate it.")
    sys.exit(1)
print("Required input file found.")


# ===========================================================================
# 1. LOAD oulad_task_level_leakage_free.csv AND RE-ATTACH id_student /
#    code_module / code_presentation FOR GROUPING
#
#    train_priority_model.py drops these identifier columns before saving
#    the leakage-free CSV (correctly - they must never be model FEATURES).
#    Clustering is a different job: it needs student identity purely to
#    GROUP rows, not to predict anything, so re-attaching identity here is
#    not a leakage concern.
#
#    The CSV's row order is exactly student_assessment JOIN assessments
#    (inner), sorted by [id_student, code_module, code_presentation, date]
#    (see train_priority_model.py section 2) - so re-running that same
#    load + inner-join + sort on the raw files reproduces the identical row
#    order, letting us re-attach identity columns positionally. We verify
#    this alignment below (date/weight must match exactly) before trusting it.
# ===========================================================================
section("1. RE-ATTACH id_student / code_module / code_presentation FOR GROUPING")

leak_free_df = pd.read_csv(LEAKAGE_FREE_CSV)
print(f"Loaded leakage-free dataset: {leak_free_df.shape}")

student_assessment = pd.read_csv(os.path.join(DATASETS_DIR, "studentAssessment.csv"))
student_assessment = student_assessment[student_assessment["score"] != "?"].copy()
student_assessment["score"] = student_assessment["score"].astype(float)

assessments = pd.read_csv(os.path.join(DATASETS_DIR, "assessments.csv"))
assessments = assessments[assessments["date"] != "?"].copy()
assessments["date"] = assessments["date"].astype(int)

identity_df = student_assessment.merge(assessments, on="id_assessment", how="inner")
identity_df = identity_df.sort_values(
    ["id_student", "code_module", "code_presentation", "date"]
).reset_index(drop=True)

assert len(identity_df) == len(leak_free_df), (
    f"Row count mismatch ({len(identity_df)} vs {len(leak_free_df)}) - the leakage-free CSV was "
    f"likely generated by a different version of train_priority_model.py. Re-run it to regenerate."
)

# Sanity check the positional alignment actually lines up before trusting it.
date_matches = (identity_df["date"].values == leak_free_df["date"].values).mean()
weight_matches = (identity_df["weight"].values == leak_free_df["weight"].values).mean()
print(f"Alignment check: date columns match {date_matches:.1%} of rows, weight columns match {weight_matches:.1%} of rows.")
if date_matches < 0.999 or weight_matches < 0.999:
    print("ERROR: row alignment between the raw rebuild and the leakage-free CSV does not check out.")
    print("  This likely means train_priority_model.py's join/sort logic changed. Re-run it, "
          "or re-derive identity columns explicitly rather than positionally.")
    sys.exit(1)
print("Alignment verified - safe to attach identity columns positionally.")

task_df = pd.concat(
    [identity_df[["id_student", "code_module", "code_presentation"]], leak_free_df],
    axis=1,
)


# ===========================================================================
# 2. AGGREGATE TO ONE ROW PER (id_student, code_module, code_presentation)
#
#    avg_weekly_clicks / clicks_trend / active_weeks_ratio / has_vle_activity
#    are already constant across every task-row of the same student-module
#    (they were merged in from a per-student-module VLE summary table in
#    train_priority_model.py), so .first() just reads that constant value.
#    Likewise num_of_prev_attempts / studied_credits come from studentInfo
#    and are constant per student-module.
#
#    prior_avg_score DOES vary per task-row (it's an expanding mean, by
#    design, for the classifier). For clustering we want a single behavioral
#    summary per student-module, so we take its mean across that student's
#    tasks in the module - a descriptive aggregate of their performance
#    level, which is fine here since clustering is unsupervised and has no
#    leakage constraint (unlike the classifier's per-task feature).
# ===========================================================================
section("2. AGGREGATE TO ONE ROW PER STUDENT-MODULE")

agg_spec = {
    "avg_weekly_clicks": "first",
    "clicks_trend": "first",
    "active_weeks_ratio": "first",
    "has_vle_activity": "first",
    "prior_avg_score": "mean",
    "num_of_prev_attempts": "first",
    "studied_credits": "first",
}
student_behavior = (
    task_df.groupby(["id_student", "code_module", "code_presentation"])
    .agg(agg_spec)
    .reset_index()
)
print(f"Aggregated to {len(student_behavior)} student-module rows "
      f"(from {len(task_df)} task-level rows).")


# ===========================================================================
# 3. SET ASIDE STUDENTS WITH NO VLE ACTIVITY, THEN CLIP + SCALE THE REST
#
#    Students with has_vle_activity == 0 have avg_weekly_clicks,
#    clicks_trend, and active_weeks_ratio all exactly 0 by construction (see
#    train_priority_model.py section 1b). That makes them behaviorally
#    degenerate for clustering: they're identical to each other on 3 of 7
#    features and trivially far from everyone else, so KMeans just isolates
#    them as their own "cluster" for every k tried, regardless of how many
#    clusters we ask for - drowning out any real behavioral segmentation
#    among the vast majority of students who do have engagement data. We
#    give them a fixed, directly-justified label instead of a model-derived
#    one, and cluster only the students with real engagement signal.
#
#    Among that remaining population, avg_weekly_clicks and clicks_trend are
#    still unbounded click counts with heavy right tails (a few very
#    high-activity students) - we winsorize both at the 1st/99th percentile
#    before scaling, a standard fix for heavy-tailed count data, so a
#    handful of extreme values don't dominate Euclidean distance the same way.
# ===========================================================================
section("3. SET ASIDE NO-VLE-ACTIVITY STUDENTS, CLIP + SCALE THE REST")

no_activity_mask = student_behavior["has_vle_activity"] == 0
print(f"Students with no VLE activity recorded: {int(no_activity_mask.sum())} "
      f"({no_activity_mask.mean():.2%}) - set aside with a fixed label, not clustered.")

CLUSTER_COLS = [c for c in BEHAVIOR_COLS if c != "has_vle_activity"]
clustered_pop = student_behavior.loc[~no_activity_mask].reset_index(drop=True)

X_behavior = clustered_pop[CLUSTER_COLS].copy()
for col in ["avg_weekly_clicks", "clicks_trend"]:
    lower, upper = X_behavior[col].quantile([0.01, 0.99])
    n_clipped = ((X_behavior[col] < lower) | (X_behavior[col] > upper)).sum()
    X_behavior[col] = X_behavior[col].clip(lower, upper)
    print(f"  Clipped {col} to [{lower:.1f}, {upper:.1f}] (1st/99th percentile) - {n_clipped} values affected.")

kmeans_scaler = StandardScaler()
X_scaled = kmeans_scaler.fit_transform(X_behavior)
print(f"Scaled feature matrix (engaged students only): {X_scaled.shape}")


# ===========================================================================
# 4. ELBOW METHOD + SILHOUETTE SCORE TO CHOOSE k
# ===========================================================================
section("4. DETERMINE OPTIMAL k (elbow + silhouette, k=2..8)")

k_range = range(2, 9)
inertias = []
silhouettes = []
min_cluster_fracs = []
t0 = time.time()
for k in k_range:
    km = KMeans(n_clusters=k, random_state=RANDOM_STATE, n_init=10)
    labels = km.fit_predict(X_scaled)
    inertias.append(km.inertia_)
    sil = silhouette_score(X_scaled, labels)
    silhouettes.append(sil)
    min_frac = pd.Series(labels).value_counts(normalize=True).min()
    min_cluster_fracs.append(min_frac)
    print(f"  k={k}: inertia={km.inertia_:.1f}, silhouette={sil:.4f}, smallest cluster={min_frac:.1%}  "
          f"({time.time() - t0:.1f}s elapsed)")

# A high silhouette score can come from KMeans simply isolating a handful of
# extreme outliers into their own tiny cluster (technically "well separated",
# but not a useful behavioral segment). Guard against that degenerate case by
# only considering k values whose smallest cluster holds at least 2% of
# students - i.e. treat this as a real segment, not an outlier bucket -
# before picking the best silhouette among the remaining candidates.
MIN_CLUSTER_FRACTION = 0.02
candidate_ks = [k for k, frac in zip(k_range, min_cluster_fracs) if frac >= MIN_CLUSTER_FRACTION]
if not candidate_ks:
    print(f"\nWARNING: every k in {list(k_range)} produced a cluster smaller than "
          f"{MIN_CLUSTER_FRACTION:.0%} of the data - falling back to the raw best-silhouette k.")
    candidate_ks = list(k_range)

candidate_silhouettes = [silhouettes[list(k_range).index(k)] for k in candidate_ks]
best_k = candidate_ks[int(np.argmax(candidate_silhouettes))]
best_sil = max(candidate_silhouettes)

degenerate_ks = [k for k in k_range if k not in candidate_ks]
degenerate_note = (
    f" (excluded {degenerate_ks} for producing a cluster <{MIN_CLUSTER_FRACTION:.0%} of students - "
    f"outlier isolation, not a meaningful segment)" if degenerate_ks else ""
)
print(f"\nChosen k = {best_k} (highest silhouette score among non-degenerate candidates = {best_sil:.4f}){degenerate_note}. "
      f"Silhouette is preferred over the elbow's inertia curve here because inertia decreases "
      f"monotonically with k and its 'elbow' can be subjective to read, whereas silhouette directly "
      f"measures how well-separated and cohesive the resulting clusters are - subject to the "
      f"minimum-cluster-size guard above so it doesn't just reward isolating outliers.")

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
axes[0].plot(list(k_range), inertias, marker="o", color="steelblue")
axes[0].set_title("Elbow Method: Inertia vs. k", fontsize=13)
axes[0].set_xlabel("Number of clusters (k)", fontsize=11)
axes[0].set_ylabel("Inertia (within-cluster sum of squares)", fontsize=11)
axes[0].axvline(best_k, color="darkorange", linestyle="--", label=f"Chosen k={best_k}")
axes[0].legend()

axes[1].plot(list(k_range), silhouettes, marker="o", color="seagreen")
axes[1].set_title("Silhouette Score vs. k", fontsize=13)
axes[1].set_xlabel("Number of clusters (k)", fontsize=11)
axes[1].set_ylabel("Silhouette score", fontsize=11)
axes[1].axvline(best_k, color="darkorange", linestyle="--", label=f"Chosen k={best_k}")
axes[1].legend()

fig.suptitle("K-Means Cluster Count Selection", fontsize=15)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUTS_DIR, "kmeans_elbow_silhouette.png"), dpi=300)
plt.close()
print("Saved kmeans_elbow_silhouette.png")


# ===========================================================================
# 5. FIT FINAL KMEANS
# ===========================================================================
section(f"5. FIT FINAL KMEANS (k={best_k})")

kmeans = KMeans(n_clusters=best_k, random_state=RANDOM_STATE, n_init=10)
clustered_pop["cluster"] = kmeans.fit_predict(X_scaled)
print(f"Final cluster sizes:\n{clustered_pop['cluster'].value_counts().sort_index()}")


# ===========================================================================
# 6. LABEL CLUSTERS FROM CENTROID CHARACTERISTICS
#    Centroids are in scaled (z-score) space - a positive value means "above
#    the overall average student on this feature", negative means "below".
#    We build a short descriptive name per cluster from whichever behavioral
#    traits stand out most (highest |z-score| features), rather than
#    hardcoding fixed names that might not match the real output.
# ===========================================================================
section("6. LABEL CLUSTERS FROM CENTROID CHARACTERISTICS")

centroids_scaled = pd.DataFrame(kmeans.cluster_centers_, columns=CLUSTER_COLS)
centroids_raw = clustered_pop.groupby("cluster")[CLUSTER_COLS].mean()
print("Cluster centroids (raw units, mean per cluster):")
print(centroids_raw.round(2))


def describe_cluster(z_row):
    """Turn a cluster's standardized centroid into a short descriptive name."""
    engagement = z_row["avg_weekly_clicks"] + z_row["active_weeks_ratio"]
    performance = z_row["prior_avg_score"]
    trend = z_row["clicks_trend"]
    workload = z_row["studied_credits"]
    retries = z_row["num_of_prev_attempts"]

    engagement_word = "Engaged" if engagement > 0.3 else ("Low-Engagement" if engagement < -0.3 else "Moderately-Engaged")
    performance_word = "High-Performing" if performance > 0.3 else ("Struggling" if performance < -0.3 else "Average-Performing")

    qualifiers = []
    if trend > 0.3:
        qualifiers.append("Increasing-Effort")
    elif trend < -0.3:
        qualifiers.append("Fading-Effort")
    if retries > 0.3:
        qualifiers.append("Repeat-Attempter")
    if workload > 0.3:
        qualifiers.append("Heavy-Workload")
    elif workload < -0.3:
        qualifiers.append("Light-Workload")

    name_parts = [performance_word, engagement_word] + qualifiers[:1]
    return " ".join(name_parts) + " Studier"


cluster_names = {}
for cluster_id in range(best_k):
    z_row = centroids_scaled.iloc[cluster_id]
    cluster_names[cluster_id] = describe_cluster(z_row)

print("\nCluster labels:")
for cluster_id, name in cluster_names.items():
    print(f"  Cluster {cluster_id}: \"{name}\"  (n={int((clustered_pop['cluster'] == cluster_id).sum())})")

clustered_pop["cluster_label"] = clustered_pop["cluster"].map(cluster_names)

# Re-attach the no-VLE-activity students set aside in section 3, with a fixed
# label and a cluster id of -1 (outside the 0..k-1 model-derived cluster ids,
# so it's unambiguous this group was not assigned by KMeans).
NO_ACTIVITY_LABEL = "No VLE Engagement Data"
no_activity_pop = student_behavior.loc[no_activity_mask].reset_index(drop=True).copy()
no_activity_pop["cluster"] = -1
no_activity_pop["cluster_label"] = NO_ACTIVITY_LABEL
if len(no_activity_pop) > 0:
    cluster_names[-1] = NO_ACTIVITY_LABEL
    print(f"  Cluster -1: \"{NO_ACTIVITY_LABEL}\"  (n={len(no_activity_pop)}, set aside - not KMeans-derived)")

student_behavior = pd.concat([clustered_pop, no_activity_pop], ignore_index=True)


# ===========================================================================
# 7. PCA 2D VISUALIZATION
# ===========================================================================
section("7. PCA 2D CLUSTER VISUALIZATION")

pca = PCA(n_components=2, random_state=RANDOM_STATE)
X_pca = pca.fit_transform(X_scaled)
print(f"PCA explained variance ratio: {pca.explained_variance_ratio_.round(3)} "
      f"(total: {pca.explained_variance_ratio_.sum():.1%})")

plt.figure(figsize=(10, 8))
palette = sns.color_palette("tab10", n_colors=best_k)
for cluster_id in range(best_k):
    mask = clustered_pop["cluster"] == cluster_id
    plt.scatter(
        X_pca[mask, 0], X_pca[mask, 1],
        s=12, alpha=0.5, color=palette[cluster_id],
        label=f"{cluster_id}: {cluster_names[cluster_id]}",
    )
plt.title("Student Behavioral Clusters (PCA 2D Projection)\n"
          f"(excludes {len(no_activity_pop)} students with no VLE activity, labeled separately)", fontsize=13)
plt.xlabel(f"PC1 ({pca.explained_variance_ratio_[0]:.1%} variance)", fontsize=11)
plt.ylabel(f"PC2 ({pca.explained_variance_ratio_[1]:.1%} variance)", fontsize=11)
plt.legend(title="Cluster", fontsize=9, loc="best", markerscale=2)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUTS_DIR, "kmeans_cluster_visualization.png"), dpi=300)
plt.close()
print("Saved kmeans_cluster_visualization.png")


# ===========================================================================
# 8. SAVE OUTPUTS
# ===========================================================================
section("8. SAVE OUTPUTS")

student_behavior.to_csv(os.path.join(OUTPUTS_DIR, "student_behavior_clusters.csv"), index=False)
print(f"Saved student_behavior_clusters.csv ({len(student_behavior)} rows).")

joblib.dump(kmeans, os.path.join(MODELS_DIR, "kmeans_model.joblib"))
joblib.dump(kmeans_scaler, os.path.join(MODELS_DIR, "kmeans_scaler.joblib"))
print(f"Saved kmeans_model.joblib and kmeans_scaler.joblib to {MODELS_DIR}")


# ===========================================================================
# 9. SUMMARY
# ===========================================================================
section("9. SUMMARY")
print(f"""
Summary:
- Aggregated {len(task_df)} task-level rows into {len(student_behavior)} student-module behavior profiles.
- Selected k={best_k} clusters by silhouette score (elbow + silhouette saved to kmeans_elbow_silhouette.png).
- Cluster names (inferred from centroid characteristics, not hardcoded):
""" + "\n".join(f"    {cid}: \"{name}\" (n={int((student_behavior['cluster'] == cid).sum())})"
                for cid, name in cluster_names.items()) + f"""
- Saved: kmeans_cluster_visualization.png (PCA 2D scatter), student_behavior_clusters.csv,
  kmeans_model.joblib, kmeans_scaler.joblib.
- All PNG/CSV outputs saved to: {OUTPUTS_DIR}
- Model artifacts saved to: {MODELS_DIR}
""")
print("Done.")
